### ISSUE TITLE
esphome phsensor Calibration

### ISSUE THREAD

**Issue by robertbigk** [frasskungin/esphome-phsensor#2]
Hi, I find Your project and I very want to make this Ph sensor for me:)
I don't have experience with this kind of project wire scheme very clear. But want to ask about calibration how to do that?
And how to adopt this device to a home assistant can You help the inexperienced user? I got Home Assistant but never adopt non branded device first is my Bluetooth kettle but I flash esp32 not my writer firmware.

**Comment by mlauhalu** [comment]
Hi. Firstly the integration to home assistant is achieved via esphome (https://www.home-assistant.io/integrations/esphome/). The yaml in this project is the configuration file for the esphome sensor. 

The calibration is done with at least two buffer solutions, eg one at pH 4 and another at pH 7. Then you submerge the probe in the buffer, record the voltage in esphome console and insert that into the calibration (as done on row 40-42 in the yaml).

**Comment by robertbigk** [comment]
Ok i try order parts thank You for help:) And You Use this probe and work fine?

**Comment by mlauhalu** [comment]
I'm currently not using the sensor. The original idea was to have the probe submerged for long periods in a fermentation process, but it turned out that the readings become unreliable after a while. For spot measurements I think the probe works OK.

**Comment by robertbigk** [comment]
I want to use that for the aquarium. Then long time measurement that is not suited for this purpose?

**Comment by mlauhalu** [comment]
Well I couldn't say for sure, but for my application it did not work when submerged for long periods. But then again that reached quite acidic measurements, whereas an aquarium is going to be more stable at pH neutral. I would try it out and then verify with manual measurements if the readings are correct.

**Comment by robertbigk** [comment]
ok still big thanks for answer me and help:)
