### ISSUE TITLE
New PH sensor 2.0

### ISSUE THREAD

**Issue by chris669** [frasskungin/esphome-phsensor#3]
Hi, thanks for sharing your project!
I was just ordering the components when I saw this v2 PH sensor. Do you recommend this? Elecrow Electronic DIY Kit Crowtail PH Sensor 2.0 Kit
https://a.aliexpress.com/_mLpXt2B

**Comment by mlauhalu** [comment]
Hi,

Since I don’t have any experience with that probe, I wouldn’t know. But what I can say about the probe in my project, is that readings are not accurate after being submerged for long periods. For those kind of applications I think something from atlas scientific (https://atlas-scientific.com/ph/) would be better.

**Comment by chris669** [comment]
I've seen their product. But I do not need all the functionalities of their Pool Kit. To be sure to understand, are you talking about the circuit quality, the probe, or both? Can their EZO PH CIRCUIT simply works with your project? Connected to the ESP8266??

**Comment by chris669** [comment]
I'm not a developer, but this project seems to add some info about this.
https://github.com/ruimarinho/atlas-scientific-ph-probe-calibration-esp8266

**Comment by mlauhalu** [comment]
To be honest, I’m not sure. I would somehow assume that it is the probe
itself which is the weak link in my project. As long as the circuit outputs
voltages within range then you should be able to calibrate it in the .yaml
file.

**Comment by chris669** [comment]
OK, so their Consumer Grade or Lab Grade should work with the basic board. Just have to check the connector. Or I could also still use the 15 years old probe that is still working with my swimming pool...
