### ISSUE TITLE
Issue with readings

### ISSUE THREAD

**Issue by HVPereira** [frasskungin/esphome-phsensor#4]
Hello,

I've used your diagram and I cannot get the ph sensor to provide proper values. Shouldn't we use ads1115 to connect to the ph sensor? Furthermore do you use the potenciometer to get the proper values? I'm having none sense values on my sensor and I'm wondering what I could be doing wrong here.

How did you test your sensor and calibrated it?

**Comment by mlauhalu** [comment]
See this issue for calibration: https://github.com/mlauhalu/esphome-phsensor/issues/2

The potentiometer is used to step down the voltage from 5V to 3.3V
